version: '3.7'
services:

  api:
    container_name: central_api
    image: central_api:latest
    restart: always
    ports:
      - "8000:8000"
    env_file: ../../dev.env
    volumes:
      - ../..:/app
    depends_on:
      - db
  db:
    container_name: cp_db
    image: postgres:12.0-alpine
    env_file: ../../dev.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - center_perk_postgres_data:/var/lib/postgresql/data/

volumes:
  center_perk_postgres_data:
