FROM public.ecr.aws/r4b6e9c2/python:3.9-slim-bullseye

WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

## install psycopg2 dependencies
RUN apt-get -y update \
    && apt-get -y install wget libpq-dev gcc python3-dev musl-dev redis-tools curl vim libcurl4-openssl-dev libssl-dev

# install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


# copy project
COPY . .

#CMD ["newrelic-admin", "run-program", "python", "manage.py", "runserver", "0.0.0.0:8000"]
# CMD ["/bin/bash", "-c", "ddtrace-run python manage.py runserver 0.0.0.0:8000"]
CMD ["/bin/bash", "-c", "python manage.py runserver 0.0.0.0:8000"]