# Generated by Django 3.2.21 on 2023-09-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='path/to/img', verbose_name='Image'),
        ),
    ]
